version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - echo "== Current working directory contents =="
      - ls -al
      - echo "== Checking if index.js exists =="
      - cat index.js || echo "index.js not found"
artifacts:
  files:
    - index.js
